vich_uploader:
    db_driver: orm

    mappings:
        books_files:
            uri_prefix: /assets/books/files
            upload_destination: '%kernel.project_dir%/public/assets/books/files'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' } 
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        books_images:
            uri_prefix: /assets/books/images
            upload_destination: '%kernel.project_dir%/public/assets/books/images'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: { property: 'slug' } 
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
